### ISSUE TITLE
请问oom工作模式哪个可以最大限度防止杀后台？

### ISSUE THREAD

**Issue by xushet** [XingC123/BackgroundOpt#1]
@![Screenshot_20231124-111537_后台优化.png](https://github.com/XingC123/BackgroundOpt/assets/34502902/84b305ef-a1e9-4ed7-b06a-4bf80d268683)

**Comment by xushet** [comment]
> 严格模式。但在新版MIUI(HyperOS)可能影响millet导致无法冻结(严格模式和平衡模式都会)(但我没新版系统的机器，反馈的人又是用的smillet没有用自带墓碑)。mit lite和mitombstone据反馈是不冲突的。

好的谢谢，我的系统是类原生a14，应该没有影响吧

**Comment by XingC123** [comment]
应该没问题
