### ISSUE TITLE
关于后台定时trimMemory

### ISSUE THREAD

**Issue by busyoGG** [XingC123/BackgroundOpt#2]
我观察到backgroundFirstTaskMap只有在切换到前台的时候才会把进程移出，这样后台定时执行的trimMemory就一直无法执行（即**已有任务正在等待执行(初次进入后台的回收)**）

不知道这个是不是特意设计成这样。

是否应该在添加到backgroundFirstTaskMap的时候执行完初次进后台的任务后把对应的进程移出backgroundFirstTaskMap

**Comment by XingC123** [comment]
是的，这是一个bug。其已在alpha分支中修复，但在您提出时尚未同步至远程分支，致使您没有看到最新的修改。感谢您耐心阅读源码，及指出bug所在。具体的commit请看：[fix: 后台内存回收任务冲突导致新的回收任务无法被放入](https://github.com/XingC123/BackgroundOpt/commit/75cf74bb453283c935dd1c290dcc5dceccfb2029)
